services:
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
      target: prod
    depends_on:
      - backend
      - scalar
    ports: ["80:80"]

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: prod
