services:
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
      target: dev
    expose: ["5173"]
    ports: ["0.0.0.0:5173:5173"]
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
      - VITE_HMR_HOST=localhost
      - VITE_HMR_PORT=5173
      - VITE_HMR_PROTOCOL=http

  nginx:
    image: nginx:alpine
    depends_on:
      - frontend
      - backend
      - scalar
    ports: ["80:80"]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./server/prisma:/app/prisma
      - /app/node_modules
