set shell := ["powershell.exe", "-c"]
install:
    npm install

dev:
    npm run dev

build:
    npm run build

preview:
    npm run preview

release:
    npm run build
    mkdir -p release
    cp -r dist/* release/

dev-docker:
    docker compose -f ../compose.base.yml -f ../compose.dev.yml up --build -d

stop-docker:
    docker compose -f ../compose.base.yml -f ../compose.dev.yml down

prod-docker:
    docker compose -f ../compose.base.yml -f ../compose.prod.yml up --build -d

stop-prod:
    docker compose -f ../compose.base.yml -f ../compose.prod.yml down
