set shell := ["powershell.exe", "-c"]
install:
    npm install

dev:
    npm run dev

build:
    npm run build

preview:
    npm run preview

release:
    npm run build
    mkdir -p release
    cp -r dist/* release/